// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCb-pUeYdOHQ4TVml2Vf9CusPzOU8Y2vJg',
    appId: '1:114798246639:web:29b7b85c89c74d6435791a',
    messagingSenderId: '114798246639',
    projectId: 'stanford-c9258',
    authDomain: 'stanford-c9258.firebaseapp.com',
    storageBucket: 'stanford-c9258.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZS2UpwcmUflo-82_ZdVolE8jA6yx2brs',
    appId: '1:114798246639:android:81dc025ff92e215435791a',
    messagingSenderId: '114798246639',
    projectId: 'stanford-c9258',
    storageBucket: 'stanford-c9258.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBf0knIZc6qtN6FHBD8ln8luWoQmx_5PxE',
    appId: '1:114798246639:ios:64ac51f308dd1e9935791a',
    messagingSenderId: '114798246639',
    projectId: 'stanford-c9258',
    storageBucket: 'stanford-c9258.appspot.com',
    iosBundleId: 'com.example.stanford',
  );
}
